#!/bin/bash
while [ "$select" != "Logout" -a "$select" != "Suspend" -a "$select" != "Restart" -a "$select" != "Shutdown" ]; do
      select=$(echo -e 'Logout\nSuspend\nRestart\nShutdown' | LANG=en_US.UTF-8 dmenu -nb '#2f343f' -nf '#f3f4f5' -sb '#9575cd' -sf '#f3f4f5' -fn 'SFNS Display-14' -i -p "System Menu")
      [ -z "$select" ] && exit 0
done
[ "$select" = "Logout" ] && i3-msg exit
[ "$select" = "Suspend" ] && sh $HOME/Wallpaper/lockscreen.sh && systemctl syspend
[ "$select" = "Restart" ] && systemctl reboot
[ "$select" = "Shutdown" ] && systemctl poweroff -i
exit 0
